# Backend pipeline for CI/CD

name: Backend Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: run coding style checker
        run : |
          ./scripts/go_coding_style_checker.sh

      - name: display errors
        if: always()
        run: |
          if [ -s ./scripts/gofmt_output.txt ]; then
            echo "Coding style errors found:"
            sed -n '1,200p' ./scripts/gofmt_output.txt
            while IFS= read -r line; do
              echo "::notice title=A coding style error has been found...::Formatting issue in $line"
            done < ./scripts/gofmt_output.txt
            exit 1
          else
            echo "No coding style errors found."
            exit 0
          fi

  check-build:
    needs: check-coding-style
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: install dependencies
        working-directory: ./app
        run: |
          go mod tidy
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: generate API documentation
        working-directory: ./app
        run: |
          swag init --generalInfo cmd/main.go --output docs

      - name: build the application
        working-directory: ./app
        run: |
          go build -o tili-backend cmd/main.go

      - name: Create build artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: |
            ./app/tili-backend
            ./app/docs
          include-hidden-files: true

